### ISSUE TITLE
kafka message in topic is instable

### ISSUE THREAD

**Issue by smartx-jshan** [intelsdi-x/snap-plugin-publisher-kafka#14]
Hello, 
I tested kafka plubsher using Snap V0.11 with Kafka pluign.
I user psutil (collection), passthrough (processor) and kafka (publisher).
I defined some task like this.
![task](https://cloud.githubusercontent.com/assets/19390594/16508387/6462fefa-3f6d-11e6-9007-875865357d0a.png)

And, when I see messages using this command,
$ bin/kafka-console-consumer.sh --zookeeper localhost:2181 --topic test5 --from-beginning

I saw this message.
![task1](https://cloud.githubusercontent.com/assets/19390594/16508417/a5e7d7ec-3f6d-11e6-8ea4-5c77f8df72f0.png)

How to can see messages correctly? (Formatiing Issues?)

**Comment by mjbrender** [comment]
@smartx-jshan Hi - thanks for using this! We will have to look further into what's breaking here. FYI @intelsdi-x/plugin-maintainers

**Comment by smartx-jshan** [comment]
Thanks for your response.

In my opinion, it seems to be encoding/decoding issue using sarama. 

Would you check that point?

**Comment by cr2025x1** [comment]
This issue occurs as this plugin just sends the metrics it got into sarama library just in raw binary. 

If I'm reading correctly, in kafka_integration_test.go, the test just sends a string and check if it is shown as it should be. Even if the plugin sends the string as it is in binary form, it will be shown correctly if both ends(the plugin, kafka) text encoding matches.
But this go wrong in case the data is not string. I'm not familiar with go, but I think Kafka is getting raw object data in golang's binary form.

**Comment by IzabellaRaulin** [comment]
Solved by https://github.com/intelsdi-x/snap-plugin-publisher-kafka/pull/19
