### ISSUE TITLE
Plugin Load Error when loading snap-plugin-publisher-kafka

### ISSUE THREAD

**Issue by andrzej-k** [intelsdi-x/snap-plugin-publisher-kafka#15]
**Issue reported by [smartx-jshan](https://github.com/smartx-jshan) on main snap repo - https://github.com/intelsdi-x/snap/issues/1057**

•OS version : Ubuntu 14.04.4
•Snap version: Snap v0.14-beta
•Environment details: Virtual Machine based on KVM

When loading snap-plugin-publisher-kafka, I see the error message as below.

$ snapd -t 0 -l 1
$ snapctl plugin load snap-plugin-publisher-kafka

![snap error](https://cloud.githubusercontent.com/assets/19390594/16679708/9e927396-4524-11e6-8914-9d33ebe601cd.png)

gob: name not registred for interface: "*cpolicy.ConfigPolicyNode"

However, when I use Snap v0.11-beta with kafka plugin, it works correctly.

**Comment by andrzej-k** [comment]
@smartx-jshan - this may be related to not updated Godeps. We'll take a closer look on this.

**Comment by nanliu** [comment]
After 0.15 release, seems like we need to update godeps. Here's plugin load error message on the latest build:

```
Error loading plugin:
gob: name not registered for interface: "*cpolicy.ConfigPolicyNode"
```
