### ISSUE TITLE
Connection is not closed after each publishing

### ISSUE THREAD

**Issue by cr2025x1** [intelsdi-x/snap-plugin-publisher-kafka#22]
The plugin opens a new connection to Kafka everytime when it produces a message on Kafka. However it does not close the connection after it is done. These not closed connections eventually floods the plugin and the snap task using the plugin stops.

![screenshot from 2016-07-25 18 20 53](https://cloud.githubusercontent.com/assets/7920648/17097939/ebcea606-529a-11e6-8161-40f1cccc1b02.png)
![screenshot from 2016-07-25 18 35 53](https://cloud.githubusercontent.com/assets/7920648/17097940/ebd777cc-529a-11e6-86df-c84ba87e31a4.png)

**Comment by cr2025x1** [comment]
Oops. Please ignore these references from my failed squashing attempts. 😨

**Comment by IzabellaRaulin** [comment]
Resolved by #23
