### ISSUE TITLE
not serializing published output as json

### ISSUE THREAD

**Issue by lanejlanej** [intelsdi-x/snap-plugin-publisher-kafka#24]
I am using the plugin binary for v0.15.0-beta. When data arrives in kafka it does not appear to be serialized as json.  Have been using trifecta and kafka-console-consumer.sh to inspect data. Data for metrics is definitely arriving in kafka, but it is not in json format AFAICT, and is possibly corrupted. eg.

disk_totalfloat6�`�Asource10.1.0.90:5051plugin_running_onjenkins-1-node-0�m�F#2��intelmesosagentslavevalid_framework_messagesfloat6source10.1.0.90:5051plugin_running_onjenkins-1-node-0�m�F#2��
"��[]plugin.MetricType��������
MetricType��
Namespace_��LastAdvertisedTime_�Version_Config_��Data_Tags_��Unit_

**Comment by IzabellaRaulin** [comment]
hello @lanejlanej, the plugin binary for v0.15.0-beta does not include this pull request ["The plugin now sends metrics to Kafka in JSON type"](https://github.com/intelsdi-x/snap-plugin-publisher-kafka/pull/19) which fixed your issue. Please, build this plugin from the latest master. 

A v.0.16 release will be landing shortly, and that issue you saw will be resolved in this release
